/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SendEmailResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'sendEmail' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [SendEmailResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SendEmailResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  
  return IDL.Service({
    'sendEmail' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [SendEmailResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };